apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: kube-system
spec:
  rules:
  - host: hello.info
    http:
      paths: 
      - path: /
        pathType: Prefix
      backend:
        serviceName: traefik-web-ui
        servicePort: admin
