apiVersion: v1
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress
rules:
- apiGroups: [""]
  resources: ["secrets", "endpoints", "services"]
  verbs: ["get", "watch", "list"]

- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list"]

